### ISSUE TITLE
Images in HTML Build

### ISSUE THREAD

**Issue by ChristopherFujii-ISD** [BaileyJM02/markdown-to-pdf#3]
Using the following folder structure and action configuration I am able to generate a PDF with the images embedded but the HTML build does not include images.  Hopefully it's just a minor thing on my side but I do notice the images are not copied over when the artifact is uploaded.

Folder structure:
```
docs/src/markdown.md
docs/src/images/*.jpg
docs/dest
```

And here is my action:
```
    - name: Create PDF and HTML
      uses: BaileyJM02/markdown-to-pdf@v1.0.0
      with:
        input_dir: docs/src
        images_dir: docs/src/images
        image_import: ./images
        output_dir: docs/dest

    - uses: actions/upload-artifact@v1
      with:
        name: docs
        path: docs/dest
```
Regarding the `image_import: ./images` option:

- If I DON'T include it then images do not display in either PDF or HTML (expected behavior).
- If I DO include it then images only display in the rendered PDF.  They DO NOT display in the rendered HTML file (unexpected behavior).
- If I DO include it, then the image tags are replaced with `http://localhost:3000/imagename.png` in the HTML.  There are no base64 encoded images included in the output HTML.

Am I missing something here?
