### ISSUE TITLE
Given input path, /github/workspace/, was not found in filesystem! 

### ISSUE THREAD

**Issue by zhimin-z** [BaileyJM02/markdown-to-pdf#45]
Hi, thanks for your tool. I tried with it but always encounter the path not found error:
```
# .github/workflows/convert-to-pdf.yml

name: Docs to PDF
# This workflow is triggered on pushes to the repository.
on:
  workflow_dispatch: {}
  push:
    branches:
      - master
    # Paths can be used to only trigger actions when you have edited certain files, such as a file within the /docs directory
    paths:
      - '**.md'
      - 'images/**'

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: main
          output_dir: pdfs
          images_dir: docs/images
          # for example <img src="./images/file-name.png">
          image_import: images
          # Default is true, can set to false to only get PDF files
          build_html: false
      - uses: actions/upload-artifact@v1
        with:
          name: docs
          path: pdfs
```
This is my PR https://github.com/EthicalML/awesome-production-machine-learning/pull/357/files
and my error in running the workflow:
![image](https://user-images.githubusercontent.com/8592144/221980334-7726a112-95bd-4ade-9f74-07ed142821c1.png)
