### ISSUE TITLE
Is that possible to rename the generated pdf file?

### ISSUE THREAD

**Issue by zhimin-z** [BaileyJM02/markdown-to-pdf#46]

**Comment by cr2007** [comment]
You can just add another step within your GitHub Actions workflow that runs a shell command to change the PDF file name.

i.e. `mv <old-file-name>.pdf <new-file-name>.pdf`

It will run accordingly.
An example:

```yml
# Previous code

  steps:
    # More Code...
    - name: Rename PDF
      run: mv <old-file-name>.pdf <new-file-name>.pdf
```
